export const GET_LIST = "CONTRATOS/LIST";
export const SUCCESS_SNACKBAR = "ACTIONS/SHOW_SUCCESS_SNACKBAR";
export const ERROR_SNACKBAR = "ACTIONS/SHOW_ERROR_SNACKBAR";
export const HIDE_SNACKBAR = "ACTIONS/HIDE_SNACKBAR";
